Use this notebook to experiment on python functions.

In [1]:
import numpy as np

In [34]:
def softmax(feat):
    scores = None

    #############################################################################
    # TODO: Implement the forward pass of a softmax function                    #
    #############################################################################
    exps = np.exp(feat)
    scores = exps / np.sum(exps, axis=1, keepdims=True)
    #############################################################################
    #                             END OF YOUR CODE                              #
    #############################################################################
    return scores


num_classes, num_inputs = 3, 7
x = 0.001 * np.random.randn(num_inputs, num_classes)
y = np.random.randint(num_classes, size=num_inputs)

x = softmax(x)
print(x)
print(y)
yE = np.zeros_like(x)
for i in range(num_inputs):
    yE[(i, y[i])] = 1
print(yE)
probs = np.sum(yE, axis = 0) / num_inputs
print (probs)

print (probs * (-1.0 / x))
print (probs * (1 / x))

[[0.33327084 0.33321256 0.3335166 ]
 [0.33314938 0.33374729 0.33310333]
 [0.33364604 0.33298957 0.33336439]
 [0.33346885 0.33346025 0.3330709 ]
 [0.33373669 0.3331413  0.33312201]
 [0.33365682 0.33315114 0.33319204]
 [0.33344664 0.33334736 0.333206  ]]
[1 2 0 0 0 2 2]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]
[0.42857143 0.14285714 0.42857143]
[[-1.28595539 -0.42872677 -1.28500777]
 [-1.2864242  -0.42803986 -1.28660206]
 [-1.28450925 -0.42901387 -1.28559451]
 [-1.2851918  -0.42840831 -1.28672732]
 [-1.28416036 -0.42881847 -1.2865299 ]
 [-1.28446775 -0.42880581 -1.2862595 ]
 [-1.28527739 -0.42855339 -1.28620563]]
[[1.28595539 0.42872677 1.28500777]
 [1.2864242  0.42803986 1.28660206]
 [1.28450925 0.42901387 1.28559451]
 [1.2851918  0.42840831 1.28672732]
 [1.28416036 0.42881847 1.2865299 ]
 [1.28446775 0.42880581 1.2862595 ]
 [1.28527739 0.42855339 1.28620563]]


In [28]:
(1 / 0.33349656) * 0.28571429

0.8567233497101139

In [2]:
train_size = 49000
batch_size = 128
epoch = 5

print (train_size // batch_size)
print (epoch * train_size // batch_size)
print (epoch * (train_size // batch_size))

382
1914
1910
