Use this notebook to experiment on python functions.

In [1]:
import numpy as np
import tensorflow as tf

In [25]:
class Parent(object):
    def __init__(self):
        pass

class Child(Parent):
    def __init__(self, c, d):
        self.c = c
        self.d = d
        print (str.format('c = {}', self.c))
        print (str.format('d = {}', self.d))
        super(Child, self).__init__()

test = Child(1,2)
p = Parent(test)

c = 1
d = 2


TypeError: __init__() takes 1 positional argument but 2 were given

In [14]:
class Options:
    def __init__(self, num_cnn=2, num_fc=2, use_dropout=False, use_batch_norm=False, num_epoch=10, lrDecay=None):
        self.num_cnn = num_cnn
        self.num_fc = num_fc
        self.use_dropout = use_dropout
        self.use_batch_norm = use_batch_norm #Not done yet
        self.num_epoch = num_epoch
        self.lrDecay = lrDecay #Not done yet
        
    def __str__(self):
        return str.format("num_cnn = {}, num_fc = {}, use_dropout = {}, use_batch_norm = {}, num_epoch = {}, lrDecay = {}",
                         self.num_cnn, self.num_fc, self.use_dropout, self.use_batch_norm, self.num_epoch, self.lrDecay)
        

In [15]:
print (Options())
print (Options(num_cnn = 5, num_fc = 3, use_dropout=True, use_batch_norm=True, num_epoch=20, lrDecay=1e-4))

num_cnn = 2, num_fc = 2, use_dropout = False, use_batch_norm = False, num_epoch = 10, lrDecay = None
num_cnn = 5, num_fc = 3, use_dropout = True, use_batch_norm = True, num_epoch = 20, lrDecay = 0.0001


In [12]:
tf.reset_default_graph()

a = tf.placeholder(tf.int64, [None, None])
avg = tf.reduce_mean(a, axis=1)

In [13]:
with tf.Session() as sess:
    input = (10 * np.random.rand(3, 5)).astype(int)
    print ("input:")
    print (input)
    feed_dict = {a: input}
    output = sess.run(avg, feed_dict=feed_dict)
    print ("output:")
    print (output)

input:
[[6 0 3 4 2]
 [8 5 8 4 6]
 [9 1 4 1 2]]
output:
[3 6 3]


In [50]:
a = (10 * np.random.rand(2, 3)).astype(int)
print ("a:")
print (a)
C_reshaped = np.reshape(a, [1, np.prod(a.shape)], order = 'C')
F_reshaped = np.reshape(a, [1, np.prod(a.shape)], order = 'F')
print ("C_reshaped:")
print (C_reshaped)
print ("F_reshaped:")
print (F_reshaped)

a:
[[4 6 0]
 [0 6 2]]
C_reshaped:
[[4 6 0 0 6 2]]
F_reshaped:
[[4 0 6 6 0 2]]


In [45]:
a = (10 * np.random.rand(3, 1, 2)).astype(int)
print ("a:")
print (a)
print (str.format("a.shape = {}", a.shape))
dim0 = a.shape[0]
li = [x for x in range(10)] # This is somehow using numpy instead of standard list comprehension??!!
arr = np.asarray(li)
print (str.format("arr.shape = {}", arr.shape))

a:
[[[0 4]]

 [[9 4]]

 [[0 0]]]
a.shape = (3, 1, 2)


TypeError: 'numpy.int64' object is not callable

In [29]:
a = ((10 * np.random.rand(2, 3)) - 5).astype(int)
print (a)
print (a.shape[0])
range = np.ptp(a)
min = np.min(a)
scaled = (a - min) / range
print ("scaled:")
print (scaled)
a_sum = np.sum(a)
print ("divide by sum:")
print (a / a_sum)
print ("Order 1 Normalize:")
print (tf.keras.utils.normalize(a, order=1))
print ("Order 2 Normalize:")
print (tf.keras.utils.normalize(a, order=2))
print ("Softmax:")
print (softmax(a))

[[ 3  1  0]
 [ 0  1 -1]]
2
scaled:
[[1.   0.5  0.25]
 [0.25 0.5  0.  ]]
divide by sum:
[[ 0.75  0.25  0.  ]
 [ 0.    0.25 -0.25]]
Order 1 Normalize:
[[ 0.75  0.25  0.  ]
 [ 0.    0.5  -0.5 ]]
Order 2 Normalize:
[[ 0.9486833   0.31622777  0.        ]
 [ 0.          0.70710678 -0.70710678]]
Softmax:
[[0.84379473 0.1141952  0.04201007]
 [0.24472847 0.66524096 0.09003057]]


In [24]:
def softmax(feat):
    scores = None

    #############################################################################
    # TODO: Implement the forward pass of a softmax function                    #
    #############################################################################
    exps = np.exp(feat)
    scores = exps / np.sum(exps, axis=1, keepdims=True)
    #############################################################################
    #                             END OF YOUR CODE                              #
    #############################################################################
    return scores


num_classes, num_inputs = 3, 7
x = 0.001 * np.random.randn(num_inputs, num_classes)
y = np.random.randint(num_classes, size=num_inputs)

x = softmax(x)
print(x)
print(y)
yE = np.zeros_like(x)
for i in range(num_inputs):
    yE[(i, y[i])] = 1
print(yE)
probs = np.sum(yE, axis = 0) / num_inputs
print (probs)

print (probs * (-1.0 / x))
print (probs * (1 / x))

[[0.33328605 0.33276363 0.33395032]
 [0.33383507 0.33330371 0.33286123]
 [0.33330914 0.33271033 0.33398053]
 [0.3329293  0.33369299 0.33337771]
 [0.33348546 0.33327306 0.33324149]
 [0.3332882  0.33334925 0.33336255]
 [0.33358925 0.33342181 0.33298894]]
[2 1 0 0 2 2 1]


TypeError: 'numpy.int64' object is not callable

In [28]:
(1 / 0.33349656) * 0.28571429

0.8567233497101139

In [2]:
train_size = 49000
batch_size = 128
epoch = 5

print (train_size // batch_size)
print (epoch * train_size // batch_size)
print (epoch * (train_size // batch_size))

382
1914
1910
